version: '3.8'

services:
  app:
    container_name: node
    image: skuzema/home-library-node
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
    restart: on-failure
    networks:
      - net
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: skuzema/home-library-postgres
    build: ./database
    command: postgres -c logging_collector=on
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - net
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql

volumes:
  postgres_logs:
  postgres_data:

networks:
  net:
    driver: bridge
